
export default {
  en: {
    ViewMonster: {
      // title: 'Monster View Page',
      title: 'Monster {name}\'s Details',
      details: 'Details',
      name: 'Name',
      description: 'Description',
      stats: 'Stats',
      health: 'Health',
      energy: 'Energy',
      otherDetails: 'Other Details',
      favouriteFood: 'Favourite Food',
      nature: 'Nature',
      foundIn: 'Found In',
    },
  },
  ru: {
    ViewMonster: {
      title: 'Monster View Page',
      // title: 'Monster {name}\'s Details',
      details: 'Details',
      name: 'Name',
      description: 'Description',
      stats: 'Stats',
      health: 'Health',
      energy: 'Energy',
      otherDetails: 'Other Details',
      favouriteFood: 'Favourite Food',
      nature: 'Nature',
      foundIn: 'Found In',
    },
  },
  vi: {
    ViewMonster: {
      title: 'Monster View Page',
      // title: 'Monster {name}\'s Details',
      details: 'Details',
      name: 'Name',
      description: 'Description',
      stats: 'Stats',
      health: 'Health',
      energy: 'Energy',
      otherDetails: 'Other Details',
      favouriteFood: 'Favourite Food',
      nature: 'Nature',
      foundIn: 'Found In',
    },
  },
  zh: {
    ViewMonster: {
      title: 'Monster View Page',
      // title: 'Monster {name}\'s Details',
      details: 'Details',
      name: 'Name',
      description: 'Description',
      stats: 'Stats',
      health: 'Health',
      energy: 'Energy',
      otherDetails: 'Other Details',
      favouriteFood: 'Favourite Food',
      nature: 'Nature',
      foundIn: 'Found In',
    },
  },
  ja: {
    ViewMonster: {
      // title: 'モンスタービューページ',
      title: 'モンスター{name}の詳細',
      details: '詳細',
      name: 'お名前',
      description: '説明',
      stats: '統計',
      health: '健康',
      energy: 'エネルギー',
      otherDetails: 'その他の詳細',
      favouriteFood: '好きな食べ物',
      nature: '自然',
      foundIn: 'で発見',
    },
  },
};
